#!/usr/bin/env ansible-playbook

- name: zookeeper
  hosts: all
  become: true
  vars:
    service_name: zookeeper
    ansible_python_interpreter: /usr/bin/env python3
    zookeeper_package:
      version: 3.7.2
      checksum: sha512:6afbfc1afc8b9370281bd9862f37dbb1cb95ec54bb2ed4371831aa5c0f08cfee775050bd57ce5fc0836e61af27eed9f0076f54b98997dd0e15159196056e52ea
    zookeeper_jolokia_version: 1.6.0
  roles:
    - zookeeper
